#pragma once

#ifdef DEBUG

//#define LOADED_TEXTURE_LOG
//#define UNLOADING_TEXTURE_LOG
//#define ADDING_STORY_ITEM_ID_LOG
//#define GOING_ONLINE_LOG
//#define ENTITY_DESTROY_LOG
//#define SERVER_DESTROY_OBJECT_LOG
//#define SERVER_REJECT_LOG
//#define DESTROYING_OBJECT_LOG
//#define DESTROYING_BINDED_OBJECT_LOG

//#define OBJECT_NET_REGISTER_LOG
//#define OBJECT_NET_UNREGISTER_LOG

//#define ALL_XMLS_LOG
#define ALL_LINES_LOG

//#define EVALUATION_FUNCTION_LOADED_LOG
//#define EVALUATION_FUNCTION_INITIALIZED_LOG

//#define WEATHER_LOGGING

#define LOG_ACTION

//script
//#define DEBUG_DISABLE_SCRIPTS
//#define LOADING_SCRIPT_LOG

#endif // DEBUG
